name: redux_compact
description: Reduce the massive amount of boilerplate for Flutter redux application
version: 0.3.1
homepage: https://github.com/omaroskars/redux_compact

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  redux: ^5.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.16

  flutter_test:
    sdk: flutter

flutter:
