name: redux_compact
description: A new Flutter package project.
version: 0.0.1
author: omaroskars
homepage: https://github.com/omaroskars/redux_compact

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  redux: ^4.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1

  flutter_test:
    sdk: flutter

flutter:
